### PR TITLE
Fix container compatibility for docker created by k8s

### PR DESCRIPTION
**Pull request by pacepi**
Cpuset of a docker created by k8s looks like this:
    /kubepods/burstable/pod07dbb922-[SNAP]/223dc5e15b[SNAP]

Instead of checking prefix "docker", we usually get 12 char from
last '/'.
Test for docker and k8s, both of them work well. 'CID' row shows
the same string as the `docker ps`.

Test result for k8s:
~# docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
e978af4928f6        hub.byted.org/google_containers/pause-amd64:3.0   "/pause"                 39 hours ago        Up 39 hours                             k8s_POD_dp-9fe0dd7536-55fd89b474-[SNAP]

~# atop -j
NPROCS            SYSCPU             USRCPU              VSIZE              RSIZE             PSIZE             SWAPSZ              RDDSK              WRDSK             RNET              SNET              CPU             CID      1/1
   557             1h42m              2h57m              29.6G               1.3G              1.1G                 0K               1.9G              19.0G                0                 0              11%             host--------
     1             0.00s              0.00s              1028K                 4K              109K                 0K                 0K                 0K                0                 0               0%             e978af4928f6

Signed-off-by: zhenwei pi <pizhenwei@bytedance.com>

### CODE REVIEW

**Comment by pacepi** [comment]
PING @Atoptool

**Comment by pacepi** [comment]
PING @Atoptool

**Comment by pacepi** [comment]
@Atoptool  PING

**Comment by Atoptool** [comment]
Proposed solution corrected for RedHat/CentOS containers started by Docker.

**Pull request merged**
