### PR TITLE
photosyst.c: fix possible error in reading InfiniBand states

### PR DESCRIPTION
**Pull request by jubnzv**
Make sure that we successfully read data from rate file to avoid usage of uninitialized local variables.

### CODE REVIEW

**Comment by codebling** [comment]
Doesn't it try to `fopen` when it tries to `ibstat` after `ibprep`? Won't these then be pointing to uninitialised memory?

**Comment by jubnzv** [comment]
> Doesn't it try to `fopen` when it tries to `ibstat` after `ibprep`? Won't these then be pointing to uninitialised memory?

Hmm, really. We can't gracefully exit without any errors handling, so let's safely initialize our structs with default empty values. @codebling what do you think?

**Comment by codebling** [comment]
Looks good to me! I submitted a small PR to your repo that uses original tabs and moves the code block back below the `if` to minimise the diff with the original code.

**Comment by jubnzv** [comment]
Thanks for that.

**Comment by Atoptool** [comment]
Thanks!

**Pull request merged**
