### PR TITLE
Record the number of process stalls to run memory compaction

### PR DESCRIPTION
**Pull request by ShirleyFei**
Signed-off-by: Fei Li <lifei.shirley@bytedance.com>

### CODE REVIEW

**Comment by Atoptool** [comment]
Please do not modify the include file in the directory 'prev' since they are meant for compability with earlier versions.
Please also keep the parseable output compatible by adding (instead of inserting) new counters.

**Comment by ShirleyFei** [comment]
> Please do not modify the include file in the directory 'prev' since they are meant for compability with earlier versions.
> Please also keep the parseable output compatible by adding (instead of inserting) new counters.

Sorry for the late reply, and thanks for your suggestions. :) But I notice the original patch has been merged, should I prepare another patch to remove the prev/* updates and add (instead of insert) the new count in parseable.c? Looking forward to your suggestions. :)

**Comment by ShirleyFei** [comment]
> Please do not modify the include file in the directory 'prev' since they are meant for compability with earlier versions.
> Please also keep the parseable output compatible by adding (instead of inserting) new counters.
Sorry for the late reply..
Thanks for your suggestions and the modifications when merging. :) I will take care of this in future, thanks again.

**Comment by ShirleyFei** [comment]
> Please do not modify the include file in the directory 'prev' since they are meant for compability with earlier versions.
> Please also keep the parseable output compatible by adding (instead of inserting) new counters.

Sorry for the late reply, and thanks for your suggestions and the modifications when merging. :) I will take care of this in future, thanks again.

**Pull request merged**
