### PR TITLE
Support LLC collection

### PR DESCRIPTION
**Pull request by pizhenwei**
Since 2017, Linux started to support resctrl which can be used to
control QoS of CPU cache and monitor LLC(last level cache).

End user can use on an Intel platform:
 ~# mount -t resctrl resctrl -o mba_MBps /sys/fs/resctrl
Or on a AMD platform:
 ~# mount -t resctrl resctrl -o cdp /sys/fs/resctrl

Then we can find several directories like:
/sys/fs/resctrl/mon_data/mon_L3_XX

These counters can be found in doc:
https://github.com/torvalds/linux/blob/master/Documentation/x86/resctrl.rst

On AMD Rome/Milan, there are several dies in a socket, and each die
uses it's own L3 cache. With this patch, we can distinguish memory
bandwidth of each die to know workload is balanced or not.

Or course, on a legacy platform, all the CPU cores share a single L3
cache in a socket, we can know the memory bandwidth and cache usage
of the full socket.

Signed-off-by: zhenwei pi <pizhenwei@bytedance.com>

### CODE REVIEW

**Comment by pizhenwei** [comment]
Add example on AMD Zen3, run memory workload on LLC00 & LLC15, atop shows:
```
ATOP - n139-121-135             2022/01/05  16:02:13             --f--------------               10s elapsed
PRC |  sys    2.63s  |  user   2m04s  |  #proc   1988  |   #tslpu  1097  |  #zombie    0  |  #exit    226  |
CPU |  sys       7%  |  user   1248%  |  irq      20%  |   idle  24342%  |  wait      0%  |  curf 2.47GHz  |
CPL |  avg1    9.14  |  avg5   10.99  |  avg15   8.96  |   csw   160022  |  intr  294651  |  numcpu   256  |
MEM |  tot     1.0T  |  free  905.0G  |  cache  47.9G  |   buff    1.6G  |  slab    4.0G  |  numnode    2  |
SWP |  tot     0.0M  |  free    0.0M  |  swcac   0.0M  |                 |  vmcom  12.9G  |  vmlim 484.0G  |
LLC |  tot   212.1G  |  loc   212.0G  |                |   LLC15   100%  |                |                |
LLC |  tot   185.2G  |  loc   297.7M  |                |   LLC00   100%  |                |                |
LLC |  tot   156.5M  |  loc   113.4M  |                |   LLC07    75%  |                |                |
LLC |  tot   127.5M  |  loc    93.9M  |                |   LLC02    46%  |                |                |
LLC |  tot   112.9M  |  loc    95.0M  |                |   LLC14    71%  |                |                |
LLC |  tot   111.3M  |  loc    95.5M  |                |   LLC13    52%  |                |                |
LLC |  tot   100.5M  |  loc    86.6M  |                |   LLC11    53%  |                |                |
LLC |  tot    91.4M  |  loc    76.3M  |                |   LLC12    51%  |                |                |
LLC |  tot   100.1M  |  loc    65.1M  |                |   LLC06    51%  |                |                |
LLC |  tot    90.1M  |  loc    74.9M  |                |   LLC09    44%  |                |                |
LLC |  tot    93.4M  |  loc    65.1M  |                |   LLC03    27%  |                |                |
LLC |  tot    83.8M  |  loc    70.7M  |                |   LLC10    56%  |                |                |
LLC |  tot    79.2M  |  loc    66.9M  |                |   LLC08    39%  |                |                |
LLC |  tot    80.5M  |  loc    52.3M  |                |   LLC05    30%  |                |                |
LLC |  tot    61.8M  |  loc    40.4M  |                |   LLC01    51%  |                |                |
LLC |  tot    54.5M  |  loc    34.3M  |                |   LLC04    37%  |                |                |
PAG |  compact    0  |  numamig   29  |  migrate   29  |   swin       0  |  swout      0  |  oomkill    0  |
PSI |  cpusome   0%  |  memsome   0%  |  memfull   0%  |   iosome    0%  |  iofull    0%  |  cs     1/1/1  |
DSK |       nvme0n1  |  busy      0%  |  read       0  |   write     56  |  MBw/s    0.1  |  avio 0.27 ms  |
NFC |  rpc        0  |  read       0  |  write      0  |   retxmit    0  |  autref     0  |                |
NFS |  rpc        0  |  cread      0  |  cwrit      0  |   MBcr/s   0.0  |  MBcw/s   0.0  |  netudp     0  |
NET |  transport     |  tcpi     786  |  tcpo    1209  |   udpi      18  |  udpo      18  |  tcpao     51  |
NET |  network       |  ipi      816  |  ipo     1013  |   ipfrw      0  |  deliv    816  |  icmpo      0  |
NET |  eth0      0%  |  pcki     838  |  pcko    1158  |   sp  100 Gbps  |  si  194 Kbps  |  so  462 Kbps  |
NET |  eth2      0%  |  pcki       2  |  pcko       1  |   sp  100 Gbps  |  si    0 Kbps  |  so    0 Kbps  |
IFB |  lx5_0/1   0%  |  pcki       0  |  pcko       0  |   sp  100 Gbps  |  si    0 Kbps  |  so    0 Kbps  |
IFB |  lx5_1/1   0%  |  pcki       0  |  pcko       0  |   sp  100 Gbps  |  si    0 Kbps  |  so    0 Kbps  |

```

**Comment by Atoptool** [comment]
I will review this PR start of next week.

**Comment by Atoptool** [comment]
I reviewed the PR and have some questions:

1. Could you please write some documentation for the man page of atop(1) about the meaning of the produced values (total, local, percentage)?
2. Is it necessary to mount the resctrl pseudo-filesystem explicitly before these counters are accessible?
3. In the code added to photosyst.c you check the LLC id against MAXLLC (`if (llc->id >= MAXLLC)`) while I would expect to test the array index `si->llc.nrllcs` against MAXLLC to avoid array overflow. Is there a special reason?
4. Are the LLC id's always in sequence or can there be gaps in the id numbering (unfortunately I have no access to such system to check myself)?

**Comment by pizhenwei** [comment]
> I reviewed the PR and have some questions:
> 
> 1. Could you please write some documentation for the man page of atop(1) about the meaning of the produced values (total, local, percentage)?

Sure, add this in the second patch.

> 2. Is it necessary to mount the resctrl pseudo-filesystem explicitly before these counters are accessible?

From the point of my view, atop works as a monitor agent. It should NOT affect the system actions, even mounting a pseudo-filesystem by default. How about adding a config 'auto-mount-resctrl' to control this action? If a user allows atop to do this, atop could try. (if you agree with this, I'll do this in the next patch)

> 3. In the code added to photosyst.c you check the LLC id against MAXLLC (`if (llc->id >= MAXLLC)`) while I would expect to test the array index `si->llc.nrllcs` against MAXLLC to avoid array overflow. Is there a special reason?

You are right, fixed it.

> 4. Are the LLC id's always in sequence or can there be gaps in the id numbering (unfortunately I have no access to such system to check myself)?

I tested this on both Intel & AMD, LLC id is in sequence on a modern server.
And I digged into the main logic of id calculation, see [source code](https://github.com/torvalds/linux/blob/master/arch/x86/kernel/cpu/cacheinfo.c#L1007)
```
static void get_cache_id(int cpu, struct _cpuid4_info_regs *id4_regs)
{
	struct cpuinfo_x86 *c = &cpu_data(cpu);
	unsigned long num_threads_sharing;
	int index_msb;

	num_threads_sharing = 1 + id4_regs->eax.split.num_threads_sharing;
	index_msb = get_count_order(num_threads_sharing);
	id4_regs->id = c->apicid >> index_msb;
}
```
id4_regs->id is the LLC id. c->apicid is detected from hardware by CPUID instruction, so in the high probability the LLC id is in sequence. However, we can't suppose that the LLC id's always in sequence. There is no dependence on this in current implementation.

**Comment by Atoptool** [comment]
Thanks for the information and the fixes.
I agree that atop should not mount pseudo filesystems. For me it is enough that the mount actions are described now in the man page, so no further action is needed.

**Pull request merged**
