### PR TITLE
Ignore zero size disk collection

### PR DESCRIPTION
**Pull request by pizhenwei**
Some block driver allocates lots of disks during startup, for example:
 ~# modprobe nbd
The kernel allocates 16(default) empty disks, a disk gets valid after
connecting to the target, and has a none zero size.

This case shows that only nbd0 connected and had valid size:
DSK |         nbd0  | busy      0% |  read    4482 |  write    278 | MBr/s    0.0  | MBw/s    0.0 |  avio 0.28 ms |
DSK |          sdc  | busy      0% |  read       4 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio 2.00 ms |
DSK |      nvme0n1  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd1  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd2  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd3  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd4  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd5  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd6  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd7  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd8  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |         nbd9  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |        nbd10  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |        nbd11  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |        nbd12  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |        nbd13  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |        nbd14  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |
DSK |        nbd15  | busy      0% |  read       0 |  write      0 | MBr/s    0.0  | MBw/s    0.0 |  avio  0.0 ns |

There is no need to collect an invalid disk, so ignore it.

Signed-off-by: zhenwei pi <pizhenwei@bytedance.com>

### CODE REVIEW

**Comment by Atoptool** [comment]
I agree that invalid (non-used) disks should be ignored.
In the proposed solution for every interval and every disk(partition) the size is determined again by reading /sys/block/disk/size. Wouldn't it be enough to skip a disk when the number of reads and number of writes are both zero in /proc/diskstats? That would also skip disks that have a particular size but are not used since boot.

**Comment by pizhenwei** [comment]
> I agree that invalid (non-used) disks should be ignored. In the proposed solution for every interval and every disk(partition) the size is determined again by reading /sys/block/disk/size. Wouldn't it be enough to skip a disk when the number of reads and number of writes are both zero in /proc/diskstats? That would also skip disks that have a particular size but are not used since boot.

There are different fields in diskstats in different kernel version, detailed information link:
`https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/iostats.rst`

An unlikely corner case: Only issue discard and flush to a disk since boot.
So checking /sys/block/disk/size gets exact result of an disk valid or not, but a little overhead.

**Comment by Atoptool** [comment]
I am aware of the additional fields related to discards in /proc/diskstats and already busy to implement these counters in atop. In that case I can also check if the number of reads, writes and discards are zero to skip the disk.

**Comment by pizhenwei** [comment]
> I am aware of the additional fields related to discards in /proc/diskstats and already busy to implement these counters in atop. In that case I can also check if the number of reads, writes and discards are zero to skip the disk.

OK, let this PR keep open until 'check read & write & discard' version done, then I'll close this PR.

**Comment by pizhenwei** [comment]
Close this PR. Rather than checking valid disk size, atop ignores disks that have not been used at all
(#reads, #writes and #discards are all zero).

**Pull request closed without merging**
